---

- name: Ensure Wetty paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ wetty_uid }}"
    group: "{{ wetty_gid }}"
  with_items:
    - "{{ wetty_base_path }}"
    - "{{ wetty_data_dir_path }}"

- name: Ensure Wetty support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ wetty_base_path }}/{{ item }}"
    owner: "{{ wetty_uid }}"
    group: "{{ wetty_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure Wetty container image is pulled
  community.docker.docker_image:
    name: "{{ wetty_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ wetty_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else wetty_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Wetty container network is created
  community.general.docker_network:
    name: "{{ wetty_container_network }}"
    driver: bridge

- name: Ensure Wetty systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/wetty.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ wetty_identifier }}.service"
    mode: 0640
