---

- block:
    - when: wetty_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: wetty_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-wetty
    - install-all
    - install-wetty

- block:
    - when: (not wetty_playwright_driver_enabled | bool) or (not wetty_enabled | bool)
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall_playwright_driver.yml"
  tags:
    - setup-all
    - setup-wetty

- block:
    - when: not wetty_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-wetty
