---

- name: Check existence of Wetty systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wetty_identifier }}.service"
  register: wetty_service_stat

- when: wetty_service_stat.stat.exists | bool
  block:
    - name: Ensure Wetty systemd service is stopped
      ansible.builtin.service:
        name: "{{ wetty_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Wetty systemd service does not exists
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ wetty_identifier }}.service"
        state: absent

    - name: Ensure Wetty path doesn't exist
      ansible.builtin.file:
        path: "{{ wetty_base_path }}"
        state: absent
