---

- name: Fail if required Wetty settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - wetty_hostname
    - wetty_uid
    - wetty_gid

- when: wetty_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required wetty Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - wetty_container_labels_traefik_hostname
        - wetty_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `wetty_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if wetty_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          wetty_container_labels_traefik_path_prefix (`{{ wetty_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/anonaddy`).
      when: "wetty_container_labels_traefik_path_prefix != '/' and wetty_container_labels_traefik_path_prefix[-1] == '/'"
